### ISSUE TITLE
Error while login

### ISSUE THREAD

**Issue by meghakundu** [sulivan23/movies#1]
![image](https://github.com/user-attachments/assets/4176751d-66ec-4356-ae09-79e9f0f0a7cf)
Please help with this @sulivan23

**Comment by sulivan23** [comment]
have u already tried username admin with password 12345? @meghakundu

**Comment by meghakundu** [comment]
I had tried using data given in seeder, there in seeder password mentioned
in encrypted way/md5/bcrypt

**Comment by sulivan23** [comment]
Yes, for security reason the password field must be hashed in database. And the real password is 12345.

**Comment by meghakundu** [comment]
Authentication succeeded, now for the admin role importing movie data in db
there is no such option been given. I think needs to be add, otherwise the
message used for null values is same for movie list . Can work on it .

**Comment by sulivan23** [comment]
The movie data fetch from public API, there is no needed feature to import.
